server.port=8081
# Conexao com o Banco no Docker
spring.datasource.url=jdbc:postgresql://localhost:5433/estoque_db
spring.datasource.username=henrique
spring.datasource.password=123

#Criacao de tabelas
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.operations-sorter=alpha
springdoc.api-docs.enabled=true